/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flownex_libecono_Rs232 */

#ifndef _Included_com_flownex_libecono_Rs232
#define _Included_com_flownex_libecono_Rs232
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flownex_libecono_Rs232
 * Method:    open
 * Signature: (Ljava/lang/String;IIIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_flownex_libecono_Rs232_open
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_flownex_libecono_Rs232
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flownex_libecono_Rs232_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
