/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flownex_libecono_Rs232_STOPB */

#ifndef _Included_com_flownex_libecono_Rs232_STOPB
#define _Included_com_flownex_libecono_Rs232_STOPB
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
