/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flownex_libecono_Rs232_DATAB */

#ifndef _Included_com_flownex_libecono_Rs232_DATAB
#define _Included_com_flownex_libecono_Rs232_DATAB
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
